import { DemoCategory, DemoStepsItem } from './demo-steps-item.model';
import { StepsItemStatus } from './steps-item-status.enum';
import { StepsVisibility } from './steps-visibility.enum';
import { VideoProvider } from './video-provider.enum';
import { StepDefinition } from './step-definition.model';

interface DemoCatalogueStep {
  order: number;
  kind: 'step' | 'gap' | 'card';
  title: string;
  description?: string | null;
  startSeconds: number;
  endSeconds: number;
  durationSeconds: number | null;
  autoAdvance: boolean;
  loopVideo?: boolean;
  message?: string;
  backgroundColor?: string;
  textColor?: string;
}

interface DemoCatalogueEntry {
  id: string;
  category: DemoCategory;
  title: string;
  description?: string;
  creatorDisplayName: string;
  sourceUrl: string | null;
  externalVideoId: string | null;
  useVideoContent?: boolean;
  continuousSoundtrack: boolean;
  gapSeconds: number | null;
  gapMessage: string | null;
  repeatCount?: number | null;
  steps: DemoCatalogueStep[];
}

const PUBLISHED = '2026-08-21T16:00:00Z';

const CATALOGUE: DemoCatalogueEntry[] = [
  {
    id: 'steps_demo_cook_confit',
    category: 'Cook',
    title: 'Confit Potato, Wagyu tartare, Caviar from @notorious_foodie',
    description:
      'Confit Potato, Wagyu tartare, Caviar 😍🚀 #wagyu #caviar #potato #easyrecipe #easyrecipes #asmrfood #foodtok #cooktok #fondant #fancy #dinnerwithme #homecooking #recipesoftiktok #quickrecipes #steak',
    creatorDisplayName: '@notorious_foodie',
    sourceUrl: 'https://www.tiktok.com/@notorious_foodie/video/7179661469712174342',
    externalVideoId: '7179661469712174342',
    continuousSoundtrack: false,
    gapSeconds: null,
    gapMessage: null,
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Cut the wagyu',
        description: 'Cut the wagyu into roughly 1cm cubes and add to the mixing plate',
        startSeconds: 0,
        endSeconds: 8.5,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Finely dice the shallot',
        description:
          'Cut the shallot lengthways without protruding the end, then rotate 90 degrees and chop to give a fine diced shallot. Then add to the mixing plate.',
        startSeconds: 9.2,
        endSeconds: 11.9,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Cut the pickles',
        description: 'Finely chop the pickles and add to the mixing plate',
        startSeconds: 12.5,
        endSeconds: 13.5,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Finely chop the capers',
        description: 'Finely chop the capers and add to the mixing plate',
        startSeconds: 14,
        endSeconds: 15.8,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Mince the anchovies',
        description: 'Mince the anchovies and add to the mixing plate',
        startSeconds: 16,
        endSeconds: 18.4,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Finely chop the parsley',
        description: 'Finely chop the parsley and add to the mixing plate',
        startSeconds: 18.8,
        endSeconds: 20.5,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 7,
        kind: 'step',
        title: 'Finely chop the chives',
        description:
          'Finely chop the chives and add to the mixing plate, saving some for garnish later.',
        startSeconds: 20.5,
        endSeconds: 21.6,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 8,
        kind: 'step',
        title: 'Season and mix',
        description:
          'On the mixing plate, add an egg yolk to a bed of Dijon mustard, olive oil, Worcestershire sauce, a few shakes of tabasco sauce , salt, pepper and mix all of the ingredients together to form the wagyu mix.',
        startSeconds: 22,
        endSeconds: 28,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 9,
        kind: 'step',
        title: 'Peel and slice the potatoes',
        description:
          'Peel the potatoes, then thinly slice them using a japnese mandoline or a sharp knife.',
        startSeconds: 29.3,
        endSeconds: 34,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 10,
        kind: 'step',
        title: 'Season the potatoes',
        description: 'Season the potatoes with salt and pepper',
        startSeconds: 34,
        endSeconds: 35.8,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 11,
        kind: 'step',
        title: 'Melt 3 tablespoons of duck-fat in the microwave',
        startSeconds: 36,
        endSeconds: 43,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 12,
        kind: 'step',
        title: 'Mix and layer the potatoes',
        description:
          'Mix the melted goose fat into the potatoes and then lay them out into a pre-lined baking tray before covering with another sheet of grease proof paper',
        startSeconds: 43,
        endSeconds: 49.5,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 13,
        kind: 'step',
        title: 'Oven bake, compress and chill',
        description:
          'Bake the potato tray in the oven on a low heat for 3 hours (or until you can put a knife through it without resistance). Take out and compress with some heavy cans and place in the fridge overnight.',
        startSeconds: 50,
        endSeconds: 53.9,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 14,
        kind: 'step',
        title: 'Turn out and cut the potato',
        description:
          'Take the potato tray out of the fridge, cut into roughly 4cm x 8cm (2in x 4 in) rectangles and tidy the edges.',
        startSeconds: 54,
        endSeconds: 62.6,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 15,
        kind: 'step',
        title: 'Eat some caviar',
        description: 'Take a scoop and check that the caviar is good.',
        startSeconds: 63,
        endSeconds: 69.1,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 16,
        kind: 'step',
        title: 'Deep fry the Confit Potato',
        description:
          'Lower your confit rectangles into the deep fat fryer pan to avoid them sticking together, cook until evenly golden brown and then transfer to a baking tray with a grill to allow any fat to drain off and season with flakes of sea salt.',
        startSeconds: 69.5,
        endSeconds: 75.8,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 17,
        kind: 'step',
        title: 'Plate up',
        description:
          'Lay out 3 Confit Potato rectangles per platter, top 2 with the wagyu mix, topping the third with a layer of mayonnaise/crème fraiche/sour cream. Top all of them with a spoonful of caviar and sprinkle your retained chives to garnish.',
        startSeconds: 76.5,
        endSeconds: 87.2,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
      {
        order: 18,
        kind: 'step',
        title: 'Enjoy',
        description: 'Eat the fruits of your labour, savouring every moment.',
        startSeconds: 88.5,
        endSeconds: 94,
        durationSeconds: null,
        autoAdvance: false,
        loopVideo: false,
      },
    ],
  },
  {
    id: 'steps_demo_train_hiit',
    category: 'Train',
    title: '30 Minute Bodyweight HIIT from @nicci_robinson',
    description:
      '30 Minute Bodyweight HIIT / Beginner Friendly 🔥 Save ➡️ Share ➡️ Execute All you need is 30 minute for this ultimate burn workout. No equipment and all fitness levels are showcased so No Excuses 🙌🏽 Tabata Style  30 seconds work 15 seconds rest  ✔️Squat to Knee ✔️ 3 pulse squats into calf raise ✔️ Sprawlee ✔️Jump Lunge  ✔️ Cross Jab Squats  Rest for 60 seconds then repeat  Join my Resilient app for more workouts and challenges! Available now on all app stores #hiit #bodyweight #beginnerfriendly',
    creatorDisplayName: '@nicci_robinson',
    sourceUrl: 'https://www.tiktok.com/@nicci_robinson/video/7457632822598159658',
    externalVideoId: '7457632822598159658',
    continuousSoundtrack: false,
    gapSeconds: null,
    gapMessage: null,
    repeatCount: 7,
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Squat to Knee',
        description:
          'Go from squats to knee raise with your hands on your head. Beginner: Do from standing without squats',
        startSeconds: 4,
        endSeconds: 6.5,
        durationSeconds: 30,
        autoAdvance: true,
        loopVideo: true,
      },
      {
        order: 2,
        kind: 'step',
        title: '3 Pulse Squats into a Calf Raise',
        description:
          'Pulse 3 times in a squat position, then to standing into a full calf raise. Beginner: Squat to standing',
        startSeconds: 7.5,
        endSeconds: 10.2,
        durationSeconds: 30,
        autoAdvance: true,
        loopVideo: true,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Sprawlee',
        description:
          'Press-up position jumping your feet to your hands with your hands remaining on the floor. Beginner: Press-up position stepping both feet to hands one at a time, hands remaining on the floor, then stepping them back one at a time.',
        startSeconds: 11.5,
        endSeconds: 13,
        durationSeconds: 30,
        autoAdvance: true,
        loopVideo: true,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Jump Lunges',
        startSeconds: 15.1,
        endSeconds: 16.6,
        durationSeconds: 30,
        autoAdvance: true,
        loopVideo: true,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Cross Jab Squats',
        startSeconds: 19.5,
        endSeconds: 21.5,
        durationSeconds: 30,
        autoAdvance: true,
        loopVideo: true,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Rest',
        description: 'Rest for 60 seconds',
        startSeconds: 23,
        endSeconds: 23.5,
        durationSeconds: 60,
        autoAdvance: true,
        loopVideo: false,
      },
    ],
  },
  {
    id: 'steps_demo_style_plait',
    category: 'Style',
    title: 'Beginner Hair Plait & Twist from @theellapatt',
    creatorDisplayName: '@theellapatt',
    sourceUrl: 'https://www.tiktok.com/@theellapatt/video/7601240724440616214',
    externalVideoId: '7601240724440616214',
    continuousSoundtrack: false,
    gapSeconds: 3,
    gapMessage: 'Next part...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Separate the Hair',
        description: 'Divide the section of hair cleanly before starting.',
        startSeconds: 1,
        endSeconds: 6,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Create Three Sections',
        description: 'Separate the working hair into three even strands.',
        startSeconds: 6,
        endSeconds: 12,
        durationSeconds: 30,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Start the Plait',
        description: 'Cross the outside strands into the centre to establish the plait.',
        startSeconds: 12,
        endSeconds: 20,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Add Hair',
        description: 'Pick up additional hair while continuing the pattern.',
        startSeconds: 20,
        endSeconds: 30,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Continue the Braid',
        description: 'Repeat the crossing pattern while maintaining even tension.',
        startSeconds: 30,
        endSeconds: 40,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Finish the Twist',
        description: 'Complete and secure the end of the hairstyle.',
        startSeconds: 40,
        endSeconds: 47,
        durationSeconds: 60,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_dance_pop',
    category: 'Dance',
    title: 'Learn the Pop Muzik Dance from @beginnerdancetutorials',
    creatorDisplayName: '@beginnerdancetutorials',
    sourceUrl: 'https://www.tiktok.com/@beginnerdancetutorials/video/7496236660967918890',
    externalVideoId: '7496236660967918890',
    continuousSoundtrack: true,
    gapSeconds: 3,
    gapMessage: 'Ready for the next move?',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'First Move',
        description: 'Learn the opening movement slowly.',
        startSeconds: 3,
        endSeconds: 9,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Second Move',
        description: 'Add the second part of the choreography.',
        startSeconds: 9,
        endSeconds: 15,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Combine Moves 1 & 2',
        description: 'Practise the opening two movements together.',
        startSeconds: 15,
        endSeconds: 22,
        durationSeconds: 45,
        autoAdvance: true,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Third Move',
        description: 'Learn the next section.',
        startSeconds: 22,
        endSeconds: 29,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Final Move',
        description: 'Learn the end of the sequence.',
        startSeconds: 29,
        endSeconds: 36,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Full Dance',
        description: 'Put the complete choreography together.',
        startSeconds: 37,
        endSeconds: 48,
        durationSeconds: 120,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_makeup_baddie',
    category: 'Makeup',
    title: 'Baddie Makeup Tutorial from @itsbabykelz',
    creatorDisplayName: '@itsbabykelz',
    sourceUrl: 'https://www.tiktok.com/@itsbabykelz/video/7582736145491004686',
    externalVideoId: '7582736145491004686',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next stage...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Prep the Skin',
        description: 'Prepare and hydrate the face before applying makeup.',
        startSeconds: 3,
        endSeconds: 10,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Apply Foundation',
        description: 'Apply and blend the base evenly.',
        startSeconds: 10,
        endSeconds: 18,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Conceal',
        description: 'Apply concealer to brighten and correct.',
        startSeconds: 18,
        endSeconds: 25,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Contour',
        description: 'Add and blend contour.',
        startSeconds: 25,
        endSeconds: 32,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Brows',
        description: 'Shape and define the brows.',
        startSeconds: 32,
        endSeconds: 38,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Eyes',
        description: 'Create the eye look and lashes.',
        startSeconds: 38,
        endSeconds: 48,
        durationSeconds: 300,
        autoAdvance: false,
      },
      {
        order: 7,
        kind: 'step',
        title: 'Blush & Highlight',
        description: 'Add colour and highlight.',
        startSeconds: 48,
        endSeconds: 55,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 8,
        kind: 'step',
        title: 'Lips',
        description: 'Line and finish the lips.',
        startSeconds: 55,
        endSeconds: 63,
        durationSeconds: 120,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_fix_hinge',
    category: 'Fix',
    title: 'Repair a Cabinet Door Hinge from @mercurystardust',
    creatorDisplayName: '@mercurystardust',
    sourceUrl: 'https://www.tiktok.com/@mercurystardust/video/7293688491815439662',
    externalVideoId: '7293688491815439662',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next repair step...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Inspect the Hinge',
        description: 'Identify the loose or damaged fixing.',
        startSeconds: 4,
        endSeconds: 10,
        durationSeconds: 30,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Remove the Hinge',
        description: 'Unscrew the hinge from the damaged fixing point.',
        startSeconds: 10,
        endSeconds: 18,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Repair the Screw Hole',
        description: 'Restore the damaged fixing so it can grip a screw again.',
        startSeconds: 18,
        endSeconds: 30,
        durationSeconds: 300,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Refit the Hinge',
        description: 'Position the hinge and reinstall the screws.',
        startSeconds: 30,
        endSeconds: 40,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Align the Door',
        description: 'Adjust the hinge until the cabinet door sits correctly.',
        startSeconds: 40,
        endSeconds: 50,
        durationSeconds: 120,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_make_granny',
    category: 'Make',
    title: 'Beginner Granny Square from @jaswebstar',
    creatorDisplayName: '@jaswebstar',
    sourceUrl: 'https://www.tiktok.com/@jaswebstar/video/7528578251799661855',
    externalVideoId: '7528578251799661855',
    continuousSoundtrack: false,
    gapSeconds: 3,
    gapMessage: 'Ready for the next stitch?',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Make a Slip Knot',
        description: 'Create the starting loop on the crochet hook.',
        startSeconds: 2,
        endSeconds: 7,
        durationSeconds: 45,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Create the Centre Ring',
        description: 'Chain and join the stitches to create the centre.',
        startSeconds: 7,
        endSeconds: 15,
        durationSeconds: 90,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'First Cluster',
        description: 'Crochet the first cluster of stitches into the centre.',
        startSeconds: 15,
        endSeconds: 23,
        durationSeconds: 90,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Create the Corner',
        description: 'Add the chain spacing that forms the first corner.',
        startSeconds: 23,
        endSeconds: 29,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Complete Round One',
        description: 'Repeat the cluster and corner pattern around the centre.',
        startSeconds: 29,
        endSeconds: 40,
        durationSeconds: 300,
        autoAdvance: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Start the Next Round',
        description: 'Work into the gaps from the previous round.',
        startSeconds: 40,
        endSeconds: 49,
        durationSeconds: 300,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_play_restless',
    category: 'Play',
    title: 'Restless Guitar Tutorial from @orlanbro',
    creatorDisplayName: '@orlanbro',
    sourceUrl: 'https://www.tiktok.com/@orlanbro/video/7580576145897295118',
    externalVideoId: '7580576145897295118',
    continuousSoundtrack: true,
    gapSeconds: 3,
    gapMessage: 'Next section...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Opening Notes',
        description: 'Learn the first notes of the riff.',
        startSeconds: 2,
        endSeconds: 8,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Second Phrase',
        description: 'Practise the second phrase slowly.',
        startSeconds: 8,
        endSeconds: 14,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Join the Phrases',
        description: 'Play the first two sections together.',
        startSeconds: 14,
        endSeconds: 21,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Next Chord Pattern',
        description: 'Learn the next chord or note sequence.',
        startSeconds: 21,
        endSeconds: 29,
        durationSeconds: 90,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Full Riff',
        description: 'Practise the complete riff at the demonstrated tempo.',
        startSeconds: 30,
        endSeconds: 42,
        durationSeconds: 300,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_care_skincare',
    category: 'Care',
    title: '3-Step Skincare Routine from @sabrina.cinoman.brier',
    creatorDisplayName: '@sabrina.cinoman.brier',
    sourceUrl: 'https://www.tiktok.com/@sabrina.cinoman.brier/video/7550301946347900191',
    externalVideoId: '7550301946347900191',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next skincare step...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Cleanse',
        description: 'Clean the skin before applying the remaining products.',
        startSeconds: 3,
        endSeconds: 10,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Treat',
        description: 'Apply the treatment or serum evenly.',
        startSeconds: 10,
        endSeconds: 18,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Moisturise',
        description: 'Apply moisturiser as the final stage.',
        startSeconds: 18,
        endSeconds: 27,
        durationSeconds: 60,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_learn_study',
    category: 'Learn',
    title: 'Study Tips from @gvgmotivation',
    creatorDisplayName: '@gvgmotivation',
    sourceUrl: 'https://www.tiktok.com/@gvgmotivation/video/6708742129562160389',
    externalVideoId: '6708742129562160389',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next technique...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Remove Distractions',
        description: 'Prepare a distraction-free place to work.',
        startSeconds: 2,
        endSeconds: 7,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Plan the Session',
        description: 'Decide exactly what you intend to complete.',
        startSeconds: 7,
        endSeconds: 12,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Focused Study',
        description: 'Work on the chosen topic without interruption.',
        startSeconds: 12,
        endSeconds: 18,
        durationSeconds: 1500,
        autoAdvance: true,
      },
      {
        order: 4,
        kind: 'gap',
        title: '',
        description: null,
        startSeconds: 0,
        endSeconds: 0,
        durationSeconds: 300,
        autoAdvance: true,
        message: 'Take a five-minute break',
      },
      {
        order: 5,
        kind: 'step',
        title: 'Active Recall',
        description: 'Test what you remember without referring back to the material.',
        startSeconds: 18,
        endSeconds: 24,
        durationSeconds: 300,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_learn_writing',
    category: 'Learn',
    title: 'Grammar School Creative Writing Test Timer',
    description:
      'This simulates a grammar school test for creative writing. Starting with a 5 minute planning time, there is then a 30 second gap for the announcement to move on to the main creative writing exercise followed by a 15 minutes timer for the main exercise.',
    creatorDisplayName: 'Andy',
    sourceUrl: null,
    externalVideoId: null,
    useVideoContent: false,
    continuousSoundtrack: false,
    gapSeconds: null,
    gapMessage: null,
    steps: [
      {
        order: 1,
        kind: 'card',
        title: '',
        startSeconds: 0,
        endSeconds: 0,
        durationSeconds: 300,
        autoAdvance: true,
        message: 'Planning',
        backgroundColor: '#02C998',
        textColor: '#002116',
      },
      {
        order: 2,
        kind: 'gap',
        title: '',
        startSeconds: 0,
        endSeconds: 0,
        durationSeconds: 30,
        autoAdvance: true,
        message:
          'The planning time is over, we will be starting the main creative writing section after this 30 second break.',
      },
      {
        order: 3,
        kind: 'card',
        title: '',
        startSeconds: 0,
        endSeconds: 0,
        durationSeconds: 900,
        autoAdvance: true,
        message: 'Write the creative writing piece',
        backgroundColor: '#02C998',
        textColor: '#002116',
      },
    ],
  },
];

export const CATALOGUE_DEMOS: DemoStepsItem[] = CATALOGUE.map(toDemoItem);

function toDemoItem(entry: DemoCatalogueEntry): DemoStepsItem {
  const handle = entry.creatorDisplayName.replace(/^@/, '').toLowerCase();
  const useVideo = entry.useVideoContent !== false && !!entry.externalVideoId;
  const sourceUrl =
    entry.sourceUrl ?? (useVideo && handle ? `https://www.tiktok.com/@${handle}` : '');
  const firstActivity = entry.steps.find((step) => step.kind !== 'gap');

  return {
    id: entry.id,
    category: entry.category,
    listed: true,
    createdByUserId: 'usr_demo',
    linkedPlatformAccountId: null,
    visibility: StepsVisibility.Private,
    status: StepsItemStatus.Published,
    title: entry.title,
    description: entry.description ?? firstActivity?.description ?? entry.title,
    creatorDisplayName: entry.creatorDisplayName,
    useVideoContent: useVideo,
    continuousSoundtrack: entry.continuousSoundtrack,
    gapSeconds: entry.gapSeconds,
    gapMessage: entry.gapMessage,
    repeatCount: entry.repeatCount ?? null,
    video: useVideo
      ? {
          provider: VideoProvider.TikTok,
          externalVideoId: entry.externalVideoId ?? '',
          sourceUrl,
          creatorUsername: handle,
        }
      : {
          provider: VideoProvider.None,
          externalVideoId: '',
          sourceUrl: '',
        },
    steps: entry.steps.map((step) => toStep(entry.id, step)),
    createdUtc: PUBLISHED,
    updatedUtc: PUBLISHED,
    publishedUtc: PUBLISHED,
  };
}

function toStep(demoId: string, step: DemoCatalogueStep): StepDefinition {
  const mapped: StepDefinition = {
    id: `${demoId}_step_${step.order}`,
    order: step.order,
    kind: step.kind,
    title: step.title,
    startSeconds: step.startSeconds,
    endSeconds: step.endSeconds,
    durationSeconds: step.durationSeconds,
    autoAdvance: step.autoAdvance,
  };

  if (step.description) {
    mapped.description = step.description;
  }

  if ((step.kind === 'gap' || step.kind === 'card') && step.message) {
    mapped.message = step.message;
  }

  if (step.kind === 'card') {
    mapped.backgroundColor = step.backgroundColor ?? null;
    mapped.textColor = step.textColor ?? null;
  }

  if (step.loopVideo === false) {
    mapped.loopVideo = false;
  } else if (step.loopVideo === true) {
    mapped.loopVideo = true;
  }

  return mapped;
}
