import { DemoCategory, DemoStepsItem } from './demo-steps-item.model';
import { StepsItemStatus } from './steps-item-status.enum';
import { StepsVisibility } from './steps-visibility.enum';
import { VideoProvider } from './video-provider.enum';
import { StepDefinition } from './step-definition.model';

interface DemoCatalogueStep {
  order: number;
  kind: 'step' | 'gap';
  title: string;
  description?: string | null;
  startSeconds: number;
  endSeconds: number;
  durationSeconds: number;
  autoAdvance: boolean;
  message?: string;
}

interface DemoCatalogueEntry {
  id: string;
  category: DemoCategory;
  title: string;
  creatorDisplayName: string;
  sourceUrl: string | null;
  externalVideoId: string | null;
  continuousSoundtrack: boolean;
  gapSeconds: number;
  gapMessage: string;
  steps: DemoCatalogueStep[];
}

const PUBLISHED = '2026-08-21T16:00:00Z';

const CATALOGUE: DemoCatalogueEntry[] = [
  {
    id: 'steps_demo_cook_confit',
    category: 'Cook',
    title: 'Confit Potato, Wagyu Tartare & Caviar',
    creatorDisplayName: '@notorious_foodie',
    sourceUrl: 'https://www.tiktok.com/@notorious_foodie/video/7179661469712174342',
    externalVideoId: '7179661469712174342',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Get ready for the next step...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Prepare the Potato',
        description: 'Trim and shape the potato ready for cooking.',
        startSeconds: 1,
        endSeconds: 5,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Cook the Potato',
        description: 'Cook the shaped potato in fat until tender and golden.',
        startSeconds: 5,
        endSeconds: 12,
        durationSeconds: 1200,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Prepare the Wagyu',
        description: 'Finely dice the Wagyu for the tartare.',
        startSeconds: 13,
        endSeconds: 18,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Season the Tartare',
        description: 'Combine and season the tartare mixture.',
        startSeconds: 18,
        endSeconds: 23,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Assemble',
        description: 'Place the Wagyu tartare onto the confit potato.',
        startSeconds: 24,
        endSeconds: 29,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Finish with Caviar',
        description: 'Add the final garnish and caviar.',
        startSeconds: 29,
        endSeconds: 34,
        durationSeconds: 30,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_train_hiit',
    category: 'Train',
    title: '30 Minute Bodyweight HIIT / Beginner Friendly',
    creatorDisplayName: '@nicci_robinson',
    sourceUrl: 'https://www.tiktok.com/@nicci_robinson/video/7457632822598159658',
    externalVideoId: '7457632822598159658',
    continuousSoundtrack: true,
    gapSeconds: 15,
    gapMessage: 'Rest — next exercise coming up...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Squat to Knee',
        description: 'Perform a squat, then drive one knee up towards your chest. Alternate sides.',
        startSeconds: 0,
        endSeconds: 6,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 2,
        kind: 'step',
        title: '3 Pulse Squats into Calf Raise',
        description: 'Perform three controlled squat pulses, then rise up onto your toes for a calf raise.',
        startSeconds: 6,
        endSeconds: 12,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Sprawlee',
        description: 'Drop your hands to the floor, jump or step your feet back, then return to standing.',
        startSeconds: 12,
        endSeconds: 18,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Jump Lunge',
        description: 'Alternate between lunge positions, switching legs with a jump.',
        startSeconds: 18,
        endSeconds: 24,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Cross Jab Squats',
        description: 'Squat down, then alternate cross-body punches as you rise.',
        startSeconds: 24,
        endSeconds: 30,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 6,
        kind: 'gap',
        title: '',
        description: null,
        startSeconds: 0,
        endSeconds: 0,
        durationSeconds: 60,
        autoAdvance: true,
        message: '60 second recovery — then repeat the circuit',
      },
    ],
  },
  {
    id: 'steps_demo_style_plait',
    category: 'Style',
    title: 'Beginner Hair Plait & Twist',
    creatorDisplayName: '@theellapatt',
    sourceUrl: 'https://www.tiktok.com/@theellapatt/video/7601240724440616214',
    externalVideoId: '7601240724440616214',
    continuousSoundtrack: false,
    gapSeconds: 3,
    gapMessage: 'Next part...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Separate the Hair',
        description: 'Divide the section of hair cleanly before starting.',
        startSeconds: 1,
        endSeconds: 6,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Create Three Sections',
        description: 'Separate the working hair into three even strands.',
        startSeconds: 6,
        endSeconds: 12,
        durationSeconds: 30,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Start the Plait',
        description: 'Cross the outside strands into the centre to establish the plait.',
        startSeconds: 12,
        endSeconds: 20,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Add Hair',
        description: 'Pick up additional hair while continuing the pattern.',
        startSeconds: 20,
        endSeconds: 30,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Continue the Braid',
        description: 'Repeat the crossing pattern while maintaining even tension.',
        startSeconds: 30,
        endSeconds: 40,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Finish the Twist',
        description: 'Complete and secure the end of the hairstyle.',
        startSeconds: 40,
        endSeconds: 47,
        durationSeconds: 60,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_dance_pop',
    category: 'Dance',
    title: 'Learn the Pop Muzik Dance',
    creatorDisplayName: '@beginnerdancetutorials',
    sourceUrl: 'https://www.tiktok.com/@beginnerdancetutorials/video/7496236660967918890',
    externalVideoId: '7496236660967918890',
    continuousSoundtrack: true,
    gapSeconds: 3,
    gapMessage: 'Ready for the next move?',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'First Move',
        description: 'Learn the opening movement slowly.',
        startSeconds: 3,
        endSeconds: 9,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Second Move',
        description: 'Add the second part of the choreography.',
        startSeconds: 9,
        endSeconds: 15,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Combine Moves 1 & 2',
        description: 'Practise the opening two movements together.',
        startSeconds: 15,
        endSeconds: 22,
        durationSeconds: 45,
        autoAdvance: true,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Third Move',
        description: 'Learn the next section.',
        startSeconds: 22,
        endSeconds: 29,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Final Move',
        description: 'Learn the end of the sequence.',
        startSeconds: 29,
        endSeconds: 36,
        durationSeconds: 30,
        autoAdvance: true,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Full Dance',
        description: 'Put the complete choreography together.',
        startSeconds: 37,
        endSeconds: 48,
        durationSeconds: 120,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_makeup_baddie',
    category: 'Makeup',
    title: 'Baddie Makeup Tutorial',
    creatorDisplayName: '@itsbabykelz',
    sourceUrl: 'https://www.tiktok.com/@itsbabykelz/video/7582736145491004686',
    externalVideoId: '7582736145491004686',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next stage...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Prep the Skin',
        description: 'Prepare and hydrate the face before applying makeup.',
        startSeconds: 3,
        endSeconds: 10,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Apply Foundation',
        description: 'Apply and blend the base evenly.',
        startSeconds: 10,
        endSeconds: 18,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Conceal',
        description: 'Apply concealer to brighten and correct.',
        startSeconds: 18,
        endSeconds: 25,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Contour',
        description: 'Add and blend contour.',
        startSeconds: 25,
        endSeconds: 32,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Brows',
        description: 'Shape and define the brows.',
        startSeconds: 32,
        endSeconds: 38,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Eyes',
        description: 'Create the eye look and lashes.',
        startSeconds: 38,
        endSeconds: 48,
        durationSeconds: 300,
        autoAdvance: false,
      },
      {
        order: 7,
        kind: 'step',
        title: 'Blush & Highlight',
        description: 'Add colour and highlight.',
        startSeconds: 48,
        endSeconds: 55,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 8,
        kind: 'step',
        title: 'Lips',
        description: 'Line and finish the lips.',
        startSeconds: 55,
        endSeconds: 63,
        durationSeconds: 120,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_fix_hinge',
    category: 'Fix',
    title: 'Repair a Cabinet Door Hinge',
    creatorDisplayName: '@mercurystardust',
    sourceUrl: 'https://www.tiktok.com/@mercurystardust/video/7293688491815439662',
    externalVideoId: '7293688491815439662',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next repair step...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Inspect the Hinge',
        description: 'Identify the loose or damaged fixing.',
        startSeconds: 4,
        endSeconds: 10,
        durationSeconds: 30,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Remove the Hinge',
        description: 'Unscrew the hinge from the damaged fixing point.',
        startSeconds: 10,
        endSeconds: 18,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Repair the Screw Hole',
        description: 'Restore the damaged fixing so it can grip a screw again.',
        startSeconds: 18,
        endSeconds: 30,
        durationSeconds: 300,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Refit the Hinge',
        description: 'Position the hinge and reinstall the screws.',
        startSeconds: 30,
        endSeconds: 40,
        durationSeconds: 180,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Align the Door',
        description: 'Adjust the hinge until the cabinet door sits correctly.',
        startSeconds: 40,
        endSeconds: 50,
        durationSeconds: 120,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_make_granny',
    category: 'Make',
    title: 'Beginner Granny Square',
    creatorDisplayName: '@jaswebstar',
    sourceUrl: 'https://www.tiktok.com/@jaswebstar/video/7528578251799661855',
    externalVideoId: '7528578251799661855',
    continuousSoundtrack: false,
    gapSeconds: 3,
    gapMessage: 'Ready for the next stitch?',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Make a Slip Knot',
        description: 'Create the starting loop on the crochet hook.',
        startSeconds: 2,
        endSeconds: 7,
        durationSeconds: 45,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Create the Centre Ring',
        description: 'Chain and join the stitches to create the centre.',
        startSeconds: 7,
        endSeconds: 15,
        durationSeconds: 90,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'First Cluster',
        description: 'Crochet the first cluster of stitches into the centre.',
        startSeconds: 15,
        endSeconds: 23,
        durationSeconds: 90,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Create the Corner',
        description: 'Add the chain spacing that forms the first corner.',
        startSeconds: 23,
        endSeconds: 29,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Complete Round One',
        description: 'Repeat the cluster and corner pattern around the centre.',
        startSeconds: 29,
        endSeconds: 40,
        durationSeconds: 300,
        autoAdvance: false,
      },
      {
        order: 6,
        kind: 'step',
        title: 'Start the Next Round',
        description: 'Work into the gaps from the previous round.',
        startSeconds: 40,
        endSeconds: 49,
        durationSeconds: 300,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_play_restless',
    category: 'Play',
    title: 'Restless Guitar Tutorial',
    creatorDisplayName: '@orlanbro',
    sourceUrl: 'https://www.tiktok.com/@orlanbro/video/7580576145897295118',
    externalVideoId: '7580576145897295118',
    continuousSoundtrack: true,
    gapSeconds: 3,
    gapMessage: 'Next section...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Opening Notes',
        description: 'Learn the first notes of the riff.',
        startSeconds: 2,
        endSeconds: 8,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Second Phrase',
        description: 'Practise the second phrase slowly.',
        startSeconds: 8,
        endSeconds: 14,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Join the Phrases',
        description: 'Play the first two sections together.',
        startSeconds: 14,
        endSeconds: 21,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 4,
        kind: 'step',
        title: 'Next Chord Pattern',
        description: 'Learn the next chord or note sequence.',
        startSeconds: 21,
        endSeconds: 29,
        durationSeconds: 90,
        autoAdvance: false,
      },
      {
        order: 5,
        kind: 'step',
        title: 'Full Riff',
        description: 'Practise the complete riff at the demonstrated tempo.',
        startSeconds: 30,
        endSeconds: 42,
        durationSeconds: 300,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_care_skincare',
    category: 'Care',
    title: '3-Step Skincare Routine',
    creatorDisplayName: '@sabrina.cinoman.brier',
    sourceUrl: 'https://www.tiktok.com/@sabrina.cinoman.brier/video/7550301946347900191',
    externalVideoId: '7550301946347900191',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next skincare step...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Cleanse',
        description: 'Clean the skin before applying the remaining products.',
        startSeconds: 3,
        endSeconds: 10,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Treat',
        description: 'Apply the treatment or serum evenly.',
        startSeconds: 10,
        endSeconds: 18,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Moisturise',
        description: 'Apply moisturiser as the final stage.',
        startSeconds: 18,
        endSeconds: 27,
        durationSeconds: 60,
        autoAdvance: false,
      },
    ],
  },
  {
    id: 'steps_demo_learn_study',
    category: 'Learn',
    title: 'Study Tips',
    creatorDisplayName: '@gvgmotivation',
    sourceUrl: 'https://www.tiktok.com/@gvgmotivation/video/6708742129562160389',
    externalVideoId: '6708742129562160389',
    continuousSoundtrack: false,
    gapSeconds: 5,
    gapMessage: 'Next technique...',
    steps: [
      {
        order: 1,
        kind: 'step',
        title: 'Remove Distractions',
        description: 'Prepare a distraction-free place to work.',
        startSeconds: 2,
        endSeconds: 7,
        durationSeconds: 60,
        autoAdvance: false,
      },
      {
        order: 2,
        kind: 'step',
        title: 'Plan the Session',
        description: 'Decide exactly what you intend to complete.',
        startSeconds: 7,
        endSeconds: 12,
        durationSeconds: 120,
        autoAdvance: false,
      },
      {
        order: 3,
        kind: 'step',
        title: 'Focused Study',
        description: 'Work on the chosen topic without interruption.',
        startSeconds: 12,
        endSeconds: 18,
        durationSeconds: 1500,
        autoAdvance: true,
      },
      {
        order: 4,
        kind: 'gap',
        title: '',
        description: null,
        startSeconds: 0,
        endSeconds: 0,
        durationSeconds: 300,
        autoAdvance: true,
        message: 'Take a five-minute break',
      },
      {
        order: 5,
        kind: 'step',
        title: 'Active Recall',
        description: 'Test what you remember without referring back to the material.',
        startSeconds: 18,
        endSeconds: 24,
        durationSeconds: 300,
        autoAdvance: false,
      },
    ],
  },
];

export const CATALOGUE_DEMOS: DemoStepsItem[] = CATALOGUE.map(toDemoItem);

function toDemoItem(entry: DemoCatalogueEntry): DemoStepsItem {
  const handle = entry.creatorDisplayName.replace(/^@/, '').toLowerCase();
  const sourceUrl = entry.sourceUrl ?? (handle ? `https://www.tiktok.com/@${handle}` : '');
  const firstActivity = entry.steps.find((step) => step.kind === 'step');

  return {
    id: entry.id,
    category: entry.category,
    listed: true,
    createdByUserId: 'usr_demo',
    linkedPlatformAccountId: null,
    visibility: StepsVisibility.Private,
    status: StepsItemStatus.Published,
    title: entry.title,
    description: firstActivity?.description ?? entry.title,
    creatorDisplayName: entry.creatorDisplayName,
    continuousSoundtrack: entry.continuousSoundtrack,
    gapSeconds: entry.gapSeconds,
    gapMessage: entry.gapMessage,
    video: {
      provider: VideoProvider.TikTok,
      externalVideoId: entry.externalVideoId ?? '',
      sourceUrl,
      creatorUsername: handle,
    },
    steps: entry.steps.map((step) => toStep(entry.id, step)),
    createdUtc: PUBLISHED,
    updatedUtc: PUBLISHED,
    publishedUtc: PUBLISHED,
  };
}

function toStep(demoId: string, step: DemoCatalogueStep): StepDefinition {
  const mapped: StepDefinition = {
    id: `${demoId}_step_${step.order}`,
    order: step.order,
    kind: step.kind,
    title: step.title,
    startSeconds: step.startSeconds,
    endSeconds: step.endSeconds,
    durationSeconds: step.durationSeconds,
    autoAdvance: step.autoAdvance,
  };

  if (step.description) {
    mapped.description = step.description;
  }

  if (step.kind === 'gap' && step.message) {
    mapped.message = step.message;
  }

  return mapped;
}
